import 'package:get/get.dart';

class LocalizationService extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          "mulai": "Start",
          "tentang aplikasi": "About Application",
          "hello": "Hello US",
          "buat akun baru": "Create New Account",
          "berhasil": "Successfully",
          "registrasi berhasil!": "Registration Successful!",
          "registrasi gagal coba lagi.": "Registration failed, please try again.",
          "terjadi kesalahan saat menghubungi server.": "An error occurred while contacting the server.",
          "gagal": "Failed",
          "mendaftar": "Register",
          "nama lengkap": "Full Name",
          "nama tidak boleh kosong": "Name cannot be empty",
          "nama belakang": "Last Name",
          "nama belakang tidak boleh kosong": "Last name cannot be empty",
          "jenis Kelamin": "Gender",
          "pilih jenis kelamin":"select gender",
          "laki laki":"male",
          "perempuan":"female",
          "tanggal lahir": "Date of Birth",
          "tanggal lahir wajib diisi": "Date of birth is required",
          "nomor telepon": "Phone Number",
          "telepon wajib diisi": "Phone number is required",
          "email": "Email",
          "email tidak valid": "Invalid email address",
          "kata sandi": "Password",
          "minimal 6 karakter": "Minimum 6 characters",
          "konfirmasi kata sandi": "Confirm Password",
          "kata sandi tidak cocok": "Passwords do not match",
          "daftar": "Register",
          "sudah punya akun?": "Already have an account?",
          "masuk": "Login",
          "selamat datang kembali": "Welcome back",
          "masuk ke akun anda": "Login to your account",
          "masukkan email anda": "Enter your email address",
          "masukkan kata sandi anda": "Enter your password",
          "lupa kata sandi?": "Forgot Password?",
          "belum punya akun?": "Don't have an account yet?",
          "login berhasil!": "Login Successful!",
          "login gagal": "Login Failed",
          "login gagal, silakan coba lagi": "Login failed, please try again",
          "terjadi kesalahan saat login'": "An error occurred while logging in",
          "selamat Datang 🌙":"Welcome 🌙",
          "tidurlah malam ini untuk hari esok yang lebih baik.": "Sleep tonight for a better tomorrow.",
          "statistik": "Statistics",
          "edukasi": "Education",
          "berita terkini tentang tidur": "Latest News on Sleep",
          "fitur berita masih dalam pengembangan.": "News feature is still under development.",
          "tips tidur sehat": "Healthy Sleep Tips",
          "beranda": "Home",
          "prediksi": "Prediction",
          "saya":"Me",
          "edit profil pengguna": "Edit User Profile",
          "keamanan & privasi": "Security & Privacy",
          "tentang_aplikasi": "About Application",
          "keluar akun": "Logout Account",
          "versi: 1.0.0": "version: 1.0.0",
          "insomnic adalah aplikasi yang dirancang untuk membantu pengguna memahami dan mengatasi masalah insomnia. aplikasi ini menyediakan informasi seputar pola tidur, edukasi, prediksi kualitas tidur, serta grafik statistik yang mudah dipahami.": "Insomnic is an application designed to help users understand and address insomnia issues. It provides information on sleep patterns, education, sleep quality predictions, and easy-to-understand statistical graphs.",
          "dikembangkan oleh": "Developed by",
          "tim insomnic": "Insomnic Team",
          "kontak": "Contact",
          "hak cipta": "Copyright",
          "kebijakan privasi": "Privacy Policy",
          "data pengguna tidak disimpan atau dibagikan ke pihak ketiga.": "User data is not stored or shared with third parties.",
          "tidur dan bangun di waktu yang sama setiap hari.": "Sleep and wake up at the same time every day.",
          "hindari kafein dan alkohol menjelang tidur.": "Avoid caffeine and alcohol before bedtime.",
          "ciptakan suasana kamar yang tenang, gelap, dan sejuk.": "Create a calm, dark, and cool bedroom environment.",
          "hindari penggunaan gadget 1 jam sebelum tidur.": "Avoid using gadgets 1 hour before bedtime.",
          "lakukan relaksasi seperti meditasi atau pernapasan dalam.": "Practice relaxation techniques like meditation or deep breathing.",
          "batasi tidur siang maksimal 30 menit.": "Limit naps to a maximum of 30 minutes.",
          "rutin berolahraga, tetapi hindari olahraga berat menjelang tidur.": "Exercise regularly, but avoid heavy workouts before bedtime.",
          "gunakan kasur dan bantal yang nyaman.": "Use a comfortable mattress and pillows.",
          "jika tidak bisa tidur, bangunlah dan lakukan aktivitas ringan.": "If you can't sleep, get up and do a light activity.",
          "buat rutinitas sebelum tidur, seperti membaca atau mandi air hangat.": "Establish a bedtime routine, such as reading or taking a warm bath.",




         







          "bahasa": "Languages",
          "pengaturan": "Settings",
          "pilih_bahasa": "Choose Languages",
          "Pilih bahasa pilihan Anda untuk melanjutkan": "Choose your preferred language to continue",
          "bantuan": "Help",
          "keluar_desk": "Are you sure want to logout?",
          "keluar": "Logout",
          "batal": "Cancel",
          "iya": "Yes",
          },
        'id_ID': {
          "mulai": "Mulai",
          "hello": "Hello ID",
          "buat akun baru": "Buat Akun Baru",
          "berhasil": "Berhasil",
          "registrasi berhasil!": "Registrasi Berhasil!",
          "registrasi gagal coba lagi.": "Registrasi gagal, silakan coba lagi.",
          "terjadi kesalahan saat menghubungi server.": "Terjadi kesalahan saat menghubungi server.",
          "gagal": "Gagal",
          "mendaftar": "Daftar",
          "nama lengkap": "Nama Lengkap",
          "nama tidak boleh kosong": "Nama tidak boleh kosong",
          "nama belakang": "Nama Belakang",
          "nama belakang tidak boleh kosong": "Nama belakang tidak boleh kosong",
          "jenis Kelamin": "Jenis Kelamin",
          "pilih jenis kelamin": "Pilih Jenis Kelamin",
          "laki-laki": "Laki-laki",
          "perempuan": "Perempuan",
          "tanggal lahir": "Tanggal Lahir",
          "tanggal lahir wajib diisi": "Tanggal lahir wajib diisi",
          "nomor telepon": "Nomor Telepon",
          "telepon wajib diisi": "Nomor telepon wajib diisi",
          "email": "Email",
          "email tidak valid": "Email tidak valid",
          "kata sandi": "Kata Sandi",
          "minimal 6 karakter": "Minimal 6 karakter",
          "konfirmasi kata sandi": "Konfirmasi Kata Sandi",
          "kata sandi tidak cocok": "Kata sandi tidak cocok",
          "daftar": "Daftar",
          "sudah punya akun?": "Sudah punya akun?",
          "masuk": "Masuk",
          "selamat datang kembali": "Selamat datang kembali",
          "masuk ke akun anda": "Masuk ke akun Anda",
          "masukkan email anda": "Masukkan email Anda",
          "masukkan kata sandi anda": "Masukkan kata sandi Anda",
          "lupa kata sandi?": "Lupa Kata Sandi?",
          "belum punya akun?": "Belum punya akun?",
          "login berhasil!": "Login Berhasil!",
          "login gagal": "Login Gagal",
          "login gagal, silakan coba lagi": "Login gagal, silakan coba lagi",
          "terjadi kesalahan saat login": "Terjadi kesalahan saat login",
          "selamat Datang 🌙": "Selamat Datang 🌙",
          "tidurlah malam ini untuk hari esok yang lebih baik.": "Tidurlah malam ini untuk hari esok yang lebih baik.",
          "statistik": "Statistik",
          "edukasi": "Edukasi",
          "berita terkini tentang tidur": "Berita Terkini tentang Tidur",
          "fitur berita masih dalam pengembangan.": "Fitur berita masih dalam pengembangan.",
          "tips tidur sehat": "Tips Tidur Sehat",
          "beranda": "Beranda",
          "prediksi": "Prediksi",
          "saya": "Saya",
          "edit profil pengguna": "Edit Profil Pengguna",
          "keamanan & privasi": "Keamanan & Privasi",
          "tentang_aplikasi": "Tentang Aplikasi",
          "keluar akun": "Keluar Akun",
          "versi: 1.0.0": "versi: 1.0.0",
          "insomnic adalah aplikasi yang dirancang untuk membantu pengguna memahami dan mengatasi masalah insomnia. aplikasi ini menyediakan informasi seputar pola tidur, edukasi, prediksi kualitas tidur, serta grafik statistik yang mudah dipahami.": "Insomnic adalah aplikasi yang dirancang untuk membantu pengguna memahami dan mengatasi masalah insomnia. Aplikasi ini menyediakan informasi seputar pola tidur, edukasi, prediksi kualitas tidur, serta grafik statistik yang mudah dipahami.",
          "dikembangkan oleh": "Dikembangkan oleh",
          "tim insomnic": "Tim Insomnic",
          "kontak": "Kontak",
          "hak cipta": "Hak Cipta",
          "kebijakan privasi": "Kebijakan Privasi",
          "data pengguna tidak disimpan atau dibagikan ke pihak ketiga.": "Data pengguna tidak disimpan atau dibagikan ke pihak ketiga.",
          "tidur dan bangun di waktu yang sama setiap hari.": "Tidur dan bangun di waktu yang sama setiap hari.",
          "hindari kafein dan alkohol menjelang tidur.": "Hindari kafein dan alkohol menjelang tidur.",
          "ciptakan suasana kamar yang tenang, gelap, dan sejuk.": "Ciptakan suasana kamar yang tenang, gelap, dan sejuk.",
          "hindari penggunaan gadget 1 jam sebelum tidur.": "Hindari penggunaan gadget 1 jam sebelum tidur.",
          "lakukan relaksasi seperti meditasi atau pernapasan dalam.": "Lakukan relaksasi seperti meditasi atau pernapasan dalam.",
          "batasi tidur siang maksimal 30 menit.": "Batasi tidur siang maksimal 30 menit.",
          "rutin berolahraga, tetapi hindari olahraga berat menjelang tidur.": "Rutin berolahraga, tetapi hindari olahraga berat menjelang tidur.",
          "gunakan kasur dan bantal yang nyaman.": "Gunakan kasur dan bantal yang nyaman.",
          "jika tidak bisa tidur, bangunlah dan lakukan aktivitas ringan.": "Jika tidak bisa tidur, bangunlah dan lakukan aktivitas ringan.",
          "buat rutinitas sebelum tidur, seperti membaca atau mandi air hangat.": "Buat rutinitas sebelum tidur, seperti membaca atau mandi air hangat.",














          "bahasa": "Bahasa",
          "pengaturan": "Pengaturan",
          "pilih_bahasa": "Pilih Bahasa",
          "Pilih bahasa pilihan Anda untuk melanjutkan": "Pilih bahasa pilihan Anda untuk melanjutkan",
          "bantuan": "Bantuan", 
          "keluar_desk": "Apakah anda yakin untuk keluar?",
          "batal": "Batal",
          "iya": "Iya",
         }
      };
}